"""A small hand-written dataset of product/movie reviews for demo purposes.

Label 1 = positive, 0 = negative.
"""

REVIEWS = [
    # positive
    ("Absolutely loved it, great quality and would buy again.", 1),
    ("The plot was gripping and the acting was great.", 1),
    ("Great value for the price, works exactly as described.", 1),
    ("A delightful surprise; I loved every minute of it.", 1),
    ("Fast shipping and the product exceeded my expectations.", 1),
    ("Beautifully shot with a wonderful soundtrack.", 1),
    ("Comfortable, sturdy, and looks fantastic.", 1),
    ("Clever writing and genuinely funny moments.", 1),
    ("Excellent build quality, feels premium and well made.", 1),
    ("One of the best films I have seen this year.", 1),
    ("Easy to set up and works perfectly.", 1),
    ("Heartwarming and beautifully acted, a great film.", 1),
    ("Fantastic sound, crisp highs and deep bass.", 1),
    ("Highly recommend, five stars, love it.", 1),
    ("Smart, funny, and full of heart.", 1),
    ("Perfect gift, my friend was thrilled and loved it.", 1),
    ("Runs smoothly and the battery lasts all day. Excellent.", 1),
    ("Engaging characters and a satisfying ending.", 1),
    ("Works great, very happy with this purchase.", 1),
    ("Stunning visuals and a powerful, moving story.", 1),
    ("Best purchase I've made all year, highly recommend.", 1),
    ("The customer service was excellent and very helpful.", 1),
    ("Wonderful performances and a beautiful ending.", 1),
    ("Good quality, good price, very happy.", 1),
    ("This is amazing, I love how well it works.", 1),
    ("Fun, charming, and surprisingly moving. Loved it.", 1),
    ("Solid product, does the job perfectly.", 1),
    ("Brilliant film, funny and clever throughout.", 1),
    ("Impressed with the quality, well worth the money.", 1),
    ("Great battery, great screen, great value.", 1),
    # negative
    ("Terrible quality, it broke after two days.", 0),
    ("Boring, predictable, and far too long.", 0),
    ("Customer service was rude and unhelpful.", 0),
    ("Waste of money. Terrible, do not recommend.", 0),
    ("The screen flickers constantly and the battery dies fast.", 0),
    ("I fell asleep halfway through. Dull and boring.", 0),
    ("Arrived damaged and the seller ignored my emails.", 0),
    ("Confusing story and awful, wooden performances.", 0),
    ("Cheap plastic that scratches easily. Poor quality.", 0),
    ("Disappointing sequel that ruins the original.", 0),
    ("Stopped working after a week, total junk.", 0),
    ("The dialogue is cringeworthy and the pacing is awful.", 0),
    ("Uncomfortable and the strap snapped. Terrible.", 0),
    ("Regret buying this, returning it tomorrow.", 0),
    ("A tedious mess with no redeeming qualities.", 0),
    ("Misleading photos, nothing like what I received. Awful.", 0),
    ("Overpriced and underwhelming, not worth the money.", 0),
    ("Poorly made and fell apart immediately.", 0),
    ("Frustrating to use and the app keeps crashing.", 0),
    ("Loud, obnoxious, and not funny at all.", 0),
    ("Worst purchase I've made, complete waste of money.", 0),
    ("Bad quality and bad service, very disappointed.", 0),
    ("Boring plot, bad acting, a disappointing film.", 0),
    ("It doesn't work at all, broke on the first day.", 0),
    ("Disappointed. The battery is awful and it feels cheap.", 0),
    ("Dull, slow, and a total waste of two hours.", 0),
    ("Poor build, poor screen, poor value.", 0),
    ("Not worth it, the quality is terrible.", 0),
    ("Rude staff and a broken product. Never again.", 0),
    ("Hated it. Boring and badly made.", 0),
]
